image: rust:1.36-stretch

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

stages:
  - build
  - publish

Build:
  stage: build
  before_script:
  - rustc --version
  - cargo --version
  script:
  - make release
  - make luxtorpeda.tar.xz
  artifacts:
    paths:
    - luxtorpeda.tar.xz
    expire_in: 1 day

pages:
  stage: publish
  script:
  - mkdir -p public/master
  - echo "deployed $(date)" > public/master/index.html
  - cp luxtorpeda.tar.xz public/master/
  artifacts:
    paths:
    - public
  only:
  - master

cache:
  paths:
    - cargo/
    - target/
